// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzCC1oj0VyL5QNdM1w6HQkHzTsSqp8AqY',
    appId: '1:766804209312:web:996958460b3c77c88d23c5',
    messagingSenderId: '766804209312',
    projectId: 'egarrison-5858f',
    authDomain: 'egarrison-5858f.firebaseapp.com',
    storageBucket: 'egarrison-5858f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuY3IjQiwkXq_2SIMCokK4C95_BGlVppc',
    appId: '1:766804209312:android:959c4388c481733a8d23c5',
    messagingSenderId: '766804209312',
    projectId: 'egarrison-5858f',
    storageBucket: 'egarrison-5858f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-M9KugZj4nT2zV-IHCcqky7NSo1r7WUE',
    appId: '1:766804209312:ios:60acf61eb1403e6e8d23c5',
    messagingSenderId: '766804209312',
    projectId: 'egarrison-5858f',
    storageBucket: 'egarrison-5858f.appspot.com',
    androidClientId: '766804209312-5ip4ca23a6df5d7tievmf6gqef63i65d.apps.googleusercontent.com',
    iosClientId: '766804209312-p16i8bud13lh68j8ou5ck5b5jmknjeck.apps.googleusercontent.com',
    iosBundleId: 'com.yeasirarefin.eGarrison',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-M9KugZj4nT2zV-IHCcqky7NSo1r7WUE',
    appId: '1:766804209312:ios:60acf61eb1403e6e8d23c5',
    messagingSenderId: '766804209312',
    projectId: 'egarrison-5858f',
    storageBucket: 'egarrison-5858f.appspot.com',
    androidClientId: '766804209312-5ip4ca23a6df5d7tievmf6gqef63i65d.apps.googleusercontent.com',
    iosClientId: '766804209312-p16i8bud13lh68j8ou5ck5b5jmknjeck.apps.googleusercontent.com',
    iosBundleId: 'com.yeasirarefin.eGarrison',
  );
}
